vim.keymap.set("n","<C-n>t", "<cmd>NERDTreeToggle<cr>")
vim.keymap.set("n","<space>ff","<cmd>Telescope find_files<cr>")
vim.keymap.set("n","<space>lg","<cmd>Telescope live_grep<cr>")
vim.keymap.set("n","<space>gss", function ()
  local s = vim.fn.input("search pattern to grep on ? \n")
  require("telescope.builtin").grep_string({ search = s})
end)

vim.keymap.set({"n","i"},"<Down>", "<Nop>")
vim.keymap.set({"n","i"},"<Up>", "<Nop>")
vim.keymap.set({"n","i"},"<Left>", "<Nop>")
vim.keymap.set({"n","i"},"<Right>", "<Nop>")